### ISSUE TITLE
Lab 03 error when compiling scss

### ISSUE THREAD

**Issue by shoveland** [scolapicchioni/spa20#4]
When first compiling SCSS in lab03, I am getting:

 error  in ./src/theme.scss

Module build failed:
undefined
         ^
      Argument `$alpha` of `rgba($color, $alpha)` must be a number
      in C:\source\repos\WebApplication1\WebApplication1\spaclient\node_modules\@material\drawer\_mixins.scss (line 64, column 11)

 @ ./src/theme.scss 4:14-139 13:3-17:5 14:22-147
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by scolapicchioni** [comment]
Thanks for pointing this out.
Now that .NET Core 2.2 is out, I'm rewriting the whole project using vue-cli 3 for the client side and .net core 2.2 for the server side. Hopefully there will be fewer inconsistencies.

**Comment by gabrieligbastos** [comment]
any update on this?

**Comment by scolapicchioni** [comment]
I'm rewriting the whole thing with vuetify and .netcore 3.0.
Lab 01 is already online, the rest will follow hopefully this week.
[Spa30](https://github.com/scolapicchioni/spa30)
Thanks for your patience.
